# El nombre que definimos es el que aparecerá y la instrucción on se emplea como el desencadenante (o trigger en inglés) del workflow. 
## En este caso un push.
# La palabra clave branches permite especificar la rama o ramas específicas donde se espera que el evento ocurra.
name: Mi primer workflow
on:
  push:
    branches: [ master ]
# Creamos el job, Mi primer job, y definimos el SO en el que debe correr para las Github actions
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    # Con esto, podemos actualizar nuestro repositorio y la próxima vez que hagamos un push a la rama master
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo
      run: |
        echo $MI_VARIABLE.
